=encoding utf8

=head1 NAME

WAFLWAFL::Manual::JA::WAFL - CRUD ジェネレータ

=head1 概要




=head1 機能

大きく分けて以下の２つがあります。
基本的には 「wafl」「wafl-simple」 という２つのスクリプトから使用することを想定しています。

=head2 簡易CRUDテンプレート生成 (wafl)

CRUDに必要なコントローラ／ディスパッチャ／ビューを自動生成します。
サンプルテンプレートはWAF毎に分かれており
以下のテンプレートを用意してあります。

１：Catalyst

２：Mojolicious

３：Amon2

また、生成されたテンプレートをそのまま利用することは想定していません。((もちろんそのまま使っても問題ないのですが))
あくまでMinimalな部分のみの生成となっていますので
生成されたテンプレートから利用したい部分のみをコピペして
実際のアプリケーションに適用していく、というシナリオとなっています。


さらに、用意されたテンプレートをカスタマイズして
自分の環境用にカスタマイズしたテンプレートから
CRUD生成することも可能です。

=head2 Simpleテンプレート生成 (wafl-simple)

スキーマとテンプレートを指定することで、
列毎の繰り返し処理をアウトプットします。
ハッシュのテンプレートなど便利だと思います


